print("hello world")
print("loading... Please wait...")
print("Мяу Мяу Мяу")
print("Музыка не музыканта")
print("Кто?")
print("Ты.")
print("Я?")
print("Да.")
print("А ты?")
print("Что?")
print("Ну, ты.")
print("Что я?")
print("Ну кто ты?")
print("Я, ты.")
print("А я?")
print("Ты - я.")